name = "growth4ward-site"
compatibility_date = "2026-03-25"
pages_build_output_dir = "."

[[d1_databases]]
binding = "growth4ward_contact"
database_name = "growth4ward-contact"
database_id = "0256ff1c-e48b-473c-b3fc-6eb017dc37e9"
